# Taps
tap 'homebrew/bundle'
tap 'oven-sh/bun'
tap 'withgraphite/tap'
tap 'shivammathur/extensions'

# Meta tools for this bundle to install properly
brew 'mas' # Mac App Store manager to install appstore apps
brew 'svn' # Needed to install fonts

# Essentials
brew 'bash' # Latest Bash version
brew 'coreutils' # Those that come with macOS are outdated
brew 'git'
brew 'gnupg' # Dependency for pass etc but slightly conflicts with gpg-suite see https://github.com/Homebrew/homebrew-core/issues/74447
brew 'grep'
brew 'pkg-config' # https://github.com/driesvints/dotfiles/issues/20
brew 'imagemagick' # Needed for PHP imagick extension
brew 'jq'
brew 'ffmpeg'
brew "openjdk"
brew 'asimov' # Exclude node_modules etc from TM backup
brew 'scrcpy' # View screen of an android device
brew 'poppler' # PDF manipulation (needed for some projects)
brew 'qpdf' # PDF manipulation (needed for some projects)
brew 'rename'
brew 'gh' # GitHub CLI

# Infrastructure tools
brew 'awscli'
brew 'b2-tools'
brew 'just' # Better than makefiles
brew 'ansible'
brew 'ansible-lint'
brew 'dive' # Inspect container images

# Git tools
brew 'git-delta' # Nice diff viewer
brew 'git-absorb' # amazing tool for better git fixup
brew 'git-town' # Simple git stacking tool
brew 'withgraphite/tap/graphite' # Advanced stacking tool with web app

# Quicklook extensions
cask 'qlmarkdown'
cask 'quicklook-json'

# Nvim & various dependencies
brew 'neovim'
brew 'wget'
brew 'ripgrep'

# Spatie Medialibrary
brew 'jpegoptim'
brew 'optipng'
brew 'pngquant'
brew 'svgo'
brew 'gifsicle'

# PHP versions + Extensions
brew 'php@8.4'
brew 'shivammathur/extensions/xdebug@8.4'
brew 'shivammathur/extensions/redis@8.4'
brew 'shivammathur/extensions/imagick@8.4'
brew 'shivammathur/extensions/swoole@8.4'

brew 'php@8.3'
brew 'shivammathur/extensions/xdebug@8.3'
brew 'shivammathur/extensions/redis@8.3'
brew 'shivammathur/extensions/imagick@8.3'
brew 'shivammathur/extensions/swoole@8.3'

brew 'php@8.2'
brew 'shivammathur/extensions/xdebug@8.2'
brew 'shivammathur/extensions/redis@8.2'
brew 'shivammathur/extensions/imagick@8.2'
brew 'shivammathur/extensions/swoole@8.2'

# Runtimes & package managers
brew 'composer'
brew 'uv' # python dependency manager
brew 'node'
brew 'deno'
brew 'oven-sh/bun/bun'
brew 'go'
brew 'rustup'
brew 'cargo-make'

# Apps
cask 'setapp' # Paid App Store for Cleanshot, TablePlus etc.
cask '1password' # Password Manager
cask '1password-cli'
cask 'arq' # Backup solution
cask 'docker'
cask 'chromium', args: { no_quarantine: true }
cask 'firefox'
cask 'tunnelblick' # OpenVPN Application to access the company VPN

# Other tools (not necessary for work)
cask 'gpg-suite' # GPG handling for signing commits and email (SSH signing can also be used instead)
cask 'imageoptim' # Tool to optimize images / svgs
cask 'jordanbaird-ice' # Bartender replacement for cleaner menubar
brew 'starship' # fancy shell prompt
cask 'iterm2' # Better terminal
cask 'rectangle' # Better snap to edge behavior than native
cask 'raycast' # Better spotlight search

# Office / Communication
cask 'signal'
cask 'tinkerwell'
cask 'microsoft-office'
cask 'microsoft-teams'
cask 'notion'
cask 'figma'
cask 'around'

# IDEs
cask 'visual-studio-code'
cask 'jetbrains-toolbox'
cask 'phpstorm'
cask 'intellij-idea-ce'
cask 'android-studio'
cask 'android-platform-tools'

# Fonts
cask 'font-fira-code'
cask 'font-fira-code-nerd-font'
cask 'font-lato'
cask 'font-open-sans'
cask 'font-roboto'
cask 'font-source-code-pro-for-powerline'
cask 'font-source-code-pro'

# cb. fonts
cask 'font-montserrat'
cask 'font-inter'
cask 'font-reenie-beanie'

# Mac App Store
mas 'Keynote', id: 409183694
mas 'Numbers', id: 409203825
mas 'Microsoft Remote Desktop', id: 1295203466

# Personal
brew 'pass' # GPG-based PW manager
cask 'tailscale'

cask 'spotify'
cask 'element'
cask 'discord'
cask 'obs'
cask 'obsidian'

mas 'Strongbox - KeePass & PwSafe', id: 897283731
mas 'Things', id: 904280696
mas 'Menu Bar Controller for Sonos', id: 1357379892
mas 'Goodnotes', id: 1444383602
